# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-10 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_albumu', models.CharField(default='nazwa Albumu', max_length=500)),
                ('temat', models.CharField(default='temat', max_length=100)),
                ('opis_albumu', models.TextField(default='opis', max_length=2000)),
                ('album_logo', models.CharField(default='link http:// do logo', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_foto', models.CharField(default='nazawa foto', max_length=250)),
                ('obraz', models.CharField(default='link http:// do obrazu', max_length=1000)),
                ('albumnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albumbum.Album')),
            ],
        ),
    ]
